name: 'Code validation'
on: [push, pull_request]

jobs:
    linter:
        name: 'Linter'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.2
            - name: 'Install dependencies'
              run: npm install
            - name: 'Run linter'
              run: npm run lint
